### ISSUE TITLE
Some bugs

### ISSUE THREAD

**Issue by hanwoolsky** [gurkenlabs/litiengine-gurk-nukem#23]
Sometimes bugs occur when we execute the source code.
<img width="961" alt="enemy" src="https://user-images.githubusercontent.com/64078893/101273823-44b55780-37dc-11eb-8b44-49f879c0474f.png">

**Comment by nightm4re94** [comment]
That's wild. We have had similar scaling issues in the past when using the Windows content scaling option. 
Try setting the scaling to 100 % and let us know if the issue persists.
![grafik](https://user-images.githubusercontent.com/26114385/101280544-0b73ec00-37ca-11eb-9d55-cd355cf5f2e4.png)

**Comment by steffen-wilke** [comment]
see gurkenlabs/litiengine#275

**Comment by nightm4re94** [comment]
The issue has been resolved by https://github.com/gurkenlabs/litiengine/commit/07eec170806d496624e40d98f1097c9c10fbdb96.
